### ISSUE TITLE
SSL certificate problems

### ISSUE THREAD

**Issue by brightblade42** [AxisCommunications/media-stream-player-js#103]
I have a web app with a number of media-stream players.  The web app is accessed over https which means I must connect to the cameras securely as well.  The cameras (P3245-V) have their default (self-signed) certificates installed (that would be ok with me).  However, the web players reject the default certificate (not a trusted certificate authority). Is there a way to set the media-stream-player to accept such a certificate or is that a browser enforced problem? 
Can I install a previously purchased ssl certificate (the same one the app itself uses) into each of the cameras and access them by ip address? Or will I run into a problem because the cameras aren't accessed by a domain name?

**Comment by lekoaf** [comment]
Hi @brightblade42!

Good question.

I'll ping @steabert and @Tigge for you. They have a much better understanding of certificates / https / SSL than I do.

**Comment by Tigge** [comment]
I think there are a few options here:

- You could tell the browser to trust your own self-signed certificate. That would however only apply to that browser/computer.

- You could access the camera over HTTP instead if that is an option

- You could install a trusted certificate. Either one you previously bought or e.g. a free Let's Encrypt certificate. This requires that you can access the camera with a domain name and install a certificate that matches that domain name.

The certificate security is handled by the browser and it is not anything that media-stream-library-js (MSL) och media-stream-player-js (MSP) can control or sidestep.

**Comment by brightblade42** [comment]
Hi @Tigge 
Thanks for the response!  So, this turns out to be an issue of my ignorance on how SSL certs work with browsers rather than something the media-stream-player can be configured to do. 
It looks like option 3 is the winner here. I believe a wildcard certificate will allow me to use a single cert for every camera on the network by using subdomains for each of the cameras. 
I would have been ok with accessing the camera stream over http but the browser did not like an https site connecting to other separate servers over http. 

Really appreciate the help!

**Comment by Alex-Wenner-FHR** [comment]
@kevin-brashears
