### ISSUE TITLE
Add resize handling to Player component

### ISSUE THREAD

**Issue by Tigge** [AxisCommunications/media-stream-player-js#12]
**Is your feature request related to a problem? Please describe.**

Add auto-resize handling to `Player`. When resizing the area the player occupies it should behave appropriately and adjust its size in a consistent way.

**Describe the solution you'd like**

The player should stay within the bounds of the area it is given, even if it is really wide or really tall.

**Additional context**

**Comment by lekoaf** [comment]
Is this still relevant @Tigge ?

**Comment by lekoaf** [comment]
Closed due to inactivity. If this is still an issue, feel free to open it up again.
