### ISSUE TITLE
Web component in a complex page won't honor attributes "variant" and "format"

### ISSUE THREAD

**Issue by lgarrido** [AxisCommunications/media-stream-player-js#126]
Hi!

I am trying to insert a media-stream-player element into a Vaadin web interface.

First I tried on vanilla HTML, like the example provided in the source tree, and an element like this works just fine, either embedding it in the HTML code or adding it using JavaScript:

```
<media-stream-player variant="basic" style="width: 352px; height: 240px;" hostname="192.168.1.63" camera="1" format="RTP_H264" resolution="352x240" secure autoplay />
```
I get some warnings on the javascript console, but everything works as expected.
```
media-stream-player.min.js:45 ignored attribute change: variant=basic
media-stream-player.min.js:45 ignored attribute change: hostname=192.168.1.63
media-stream-player.min.js:45 ignored attribute change: camera=1
media-stream-player.min.js:45 ignored attribute change: format=RTP_H264
media-stream-player.min.js:45 ignored attribute change: resolution=352x240
media-stream-player.min.js:45 ignored attribute change: secure=
media-stream-player.min.js:45 ignored attribute change: autoplay=
```
However, when I try the slightly more sophisticated approach of coding a Vaadin plugin and embedding a media-stream-player in a complex web application interface, inserting **exactly the same HTML tag** with all 8 attributes, the resulting player won't honor attributes "variant" and "format", so I get a regular player with the full control bar and a still image, since the default format is JPEG.

I realize this is a very specific, untested usage of media-stream-player, but does it ring any bell? Is there any kind of race condition or some initialization of the JS library I could try so the element reacts to all the attributes upfront?

Thanks in advance.

**Comment by lekoaf** [comment]
We've made quite a few changes of the core library the past few weeks and perhaps we forgot to check if the WebComponent still worked. I'll do that on monday and get back to you.

**Comment by lgarrido** [comment]
Thanks for the quick follow up. Based on it, I've tried other releases of media-stream-player.min.js and everything works as expected, including 3.1.2 and 4.3.0.

Unfortunately, I didn't think of making a copy of the release I was using and I overwrote it, so I'm not sure which version exhibits the described issue. 

Cheers!
