### ISSUE TITLE
Module not found: Can't resolve 'luxon'

### ISSUE THREAD

**Issue by Junaid-Amjad** [AxisCommunications/media-stream-player-js#135]
Tell us what's on your mind.
Hi i didn't mark this as bug, because i have no idea whether it is bug or a mistake from me. I installed the package using [this link](https://github.com/AxisCommunications/media-stream-player-js#as-part-of-your-react-application) but when i run the application compiler show me this error: 
`./node_modules/media-stream-player/dist/esm/Controls.js`
`Module not found: Can't resolve 'luxon' in '*\node_modules\media-stream-player\dist\esm'`

Am i missing some procedure? I am working on react using typescript. Thanks in Advance.

**Comment by lekoaf** [comment]
@Junaid-Amjad, We have luxon as a peer dependency, so you need to install this yourself.

**Comment by Junaid-Amjad** [comment]
Alright, there is 1 another dependency `styled-components` missing. After adding both dependencies, issue is resolved.

**Comment by lekoaf** [comment]
`styled-components` shouldn't be needed to run this library. It's more for developing. If that's not the case, please let me know.

**Comment by Junaid-Amjad** [comment]
I got a compiling error of `styled-components`. Without installing the library my application won't start. After installing the library, my application run successfully.
