### ISSUE TITLE
any idea on the websocket backend code?

### ISSUE THREAD

**Issue by Nidheeshv0312** [AxisCommunications/media-stream-player-js#143]
Tell us what's on your mind.

**Comment by lekoaf** [comment]
Please elaborate.

**Comment by Nidheeshv0312** [comment]
Actually i have a ipcamera, It does not have ws support, only rtsp is there, how can i achive RTSP-OVER-WEBSOCKET]

**Comment by lekoaf** [comment]
Is it an AXIS IP camera? This library specifically supports AXIS devices.

**Comment by Nidheeshv0312** [comment]
its not an axis camera, thats why.

**Comment by lekoaf** [comment]
This library is based on [media-stream-library](https://github.com/AxisCommunications/media-stream-library-js). Maybe you can try to accomplish something with that instead. It's much more difficult but should be possible.
