### ISSUE TITLE
mp4 over http from axis cam ,having issue with video feed.. what else configuration i need to do?

### ISSUE THREAD

**Issue by parthverma68** [AxisCommunications/media-stream-player-js#145]
> 
> I have an axis ipcam running on "10.102.11.250"....i have created basic demo app in react by copying Singlestream.jsx.
> I am able to see still image from axis ipcam feed  in my demo app running at localhost:3000. but when i provide same hostname and change format to MP4_H264..
>  <Player
>             hostname={"10.102.11.250"}
>             format="MP4_H264"
>             autoPlay
>             vapixParams={vapixParams}           
>         />
> but i am not able to see video feed.... The request 
> Request URL: http://10.102.11.250/axis-cgi/media.cgi?compression=0&timestamp=2&videocodec=h264&container=mp4
> Request Method: GET
> Status Code: 404 Not Found
> Remote Address: 10.102.11.250:80
> Referrer Policy: strict-origin-when-cross-origin
> --------------------------------------------------------------------------------------------------------------------------------------------
> Accept-Ranges: bytes
> Connection: close
> Content-Type: text/html; charset=ISO-8859-1
> Date: Thu, 17 Jun 2021 10:58:31 GMT
> X-RBT-CLI: Name=us-scnx-gus00-ws-03; Ver=9.10.0;
> ----------------------------------------------------------------------------------------------------------------------------------------------
> Accept: */*
> Accept-Encoding: gzip, deflate
> Accept-Language: en-US,en;q=0.9
> Authorization: Digest username="root", realm="AXIS_ACCC8E3F505F", nonce="0001efc4Y355280626e659543aba59526330726db94d70", uri="/axis-cgi/media.cgi?compression=0&timestamp=2&videocodec=h264&container=mp4", response="3c908f0d8fc91d0e3a30568f2dbd577d", qop=auth, nc=00000005, cnonce="dae077306f8caaf3"
> Connection: keep-alive
> Host: 10.102.11.250
> Referer: http://localhost:3000/
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.128 Safari/537.36
> ----------------------------------------------------------------------------------------------------------------------------------------------
> compression: 0
> timestamp: 2
> videocodec: h264
> container: mp4
> 
> where as when i open http://10.102.11.250/axis-cgi/mjpg/video.cgi is serving me video feed in browser...
> am i doing something wrong ??
> 
>

**Comment by lekoaf** [comment]
Do you get the same error when trying "RTP_H264" or "RTP_JPEG" as format?

**Comment by parthverma68** [comment]
WebSocket connection to 'ws://10.102.11.250/rtsp-over-websocket' failed.  this is the error when i try other format...

**Comment by lekoaf** [comment]
`404 Not Found` suggests to me that the device you're using does not support the MP4 format, since it's quite new.

What device and firmware version are you using?

**Comment by parthverma68** [comment]
> `404 Not Found` suggests to me that the device you're using does not support the MP4 format, since it's quite new.
> 
> What device and firmware version are you using?
> 
> What does your `vapixParams` look like?

AXIS P1354 Network Camera

Firmware version: 5.40.19
MAC address: AC:CC:8E:3F:50:5F

Copyright (C) 1995-2013, Axis Communications AB

**Comment by lekoaf** [comment]
That's probably the problem then. `rtsp-over-websocket` was introduced in firmware 6.50-ish. Right @steabert? And MP4-support is much later.

We could probably add support for legacy MJPEG streaming, but for now, I think you're stuck with JPEG / Still image.

**Comment by lekoaf** [comment]
You could try and install the LTS 6.50 firmware and see if that helps you.

https://www.axis.com/products/axis-p1354/support

**Comment by parthverma68** [comment]
i will update you once I install LTS 6.50 firmware. thankyou for support
