### ISSUE TITLE
Example with Axis PTZ controls

### ISSUE THREAD

**Issue by TannerGabriel** [AxisCommunications/media-stream-player-js#148]
The examples in this repository and the [media-stream-library](https://github.com/AxisCommunications/media-stream-library-js) repository are working well. Still, none of the examples (to my knowledge) shows how you can add controls (PTZ functionality) to your included camera. Therefore I guess that it would be quite useful for most users if they could also implement the PTZ functionality of the camera inside a custom application without the need to include the original website of the camera.

**Comment by lekoaf** [comment]
Thanks for testing the examples!

Regarding PTZ. That's... not really an easy feat to pull off. That's _a lot_ of APIs you need to talk to to get the PTZ functionality working properly for just an example. And it may differ between device models depending on if it's a "true" PTZ device or not.

But if you're interested...

**Comment by TannerGabriel** [comment]
I'm currently facing an [issue with the automation of authentication](https://github.com/AxisCommunications/media-stream-player-js/issues/101#issuecomment-865075444) of the standard Axis page, so that is a problem that I need to tackle first. Also, I'm not sure if the effort that you described will be worth it for my current project since there are more urgent/important tasks that need to be done. 

Still, it would be nice if you could point me to the needed APIs to implement this feature. This would also be useful for other people that want to implement similar functionality.

**Comment by lekoaf** [comment]
Here you go.
https://www.axis.com/vapix-library/subjects/t10037719/section/t10036011/display
