### ISSUE TITLE
WebComponent - Defaults to Still Image. No Autoplay. Can't Dismiss stats

### ISSUE THREAD

**Issue by butlermatt** [AxisCommunications/media-stream-player-js#16]
**Describe the bug**
When I import the minified file (media-stream-player.min.js) and add the webcomponent with the host hard-coded there are a few issues I encounter:
1) There appears to be no autoplay for the webcomponent. I must hit the play button.
2) When I hit play, it defaults to "still image" even though settings shows H264 over RTP selected for the format.
3) When I press the stats button, the overlay appears. Pressing the button again does not hide the stats. Requires a full page refresh to hide the stats.

**To Reproduce**
```html
<!DOCTYPE html>
<html>
<head>
    <title>Example video streaming from Axis camera</title>
</head>

<body>
<div style="display: flex; width: 100%">
    <media-stream-player hostname="<my ip>" style="height:100%;width:100%;"/>
</div>
<script src="media-stream-player.min.js"></script>
</body>
</html>
```

1. Set up: Above code.
2. Do this: Press play. Press configuration and stats button. Notice "Type" is "still image"
3. Change format to still image, then back to H.264 over RTP. Now playing video.

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS 10.15.4
 - Browser: Chrome and Brave
 - Version: Compiled from master branch today.

**Comment by AnderssonChristian** [comment]
Hi there.

Regarding (1), you could add the `autoPlay="true"` attribute to make the component play automatically.

That being said, most modern browsers will prevent autoplay of video with audio unless certain criteria are met. Read more about this [here](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) and [here](https://hacks.mozilla.org/2019/02/firefox-66-to-block-automatically-playing-audible-video-and-audio/) for Chrome and Firefox respectively.

If your video has no audio, or if you don't mind it autoplaying with no audio, you could manually turn off audio. Here's how you could do that:

```
document.querySelector('media-stream-player').volume = 0;
```

As for (2), there might be an issue with the statusbar, but you can specify which format with the `format="H264"` attribute as a work-around.

**Comment by butlermatt** [comment]
@AnderssonChristian Thanks your for response. I believe those steps may work for using the React component (eg Player) However it does not appear that the standalone webcomponent binds autoplay or format parameters. The only attribute it passes to the player appears to be the hostname. 
https://github.com/AxisCommunications/media-stream-player-js/blob/master/lib/MediaStreamPlayer.tsx#L46

I admittedly am not a regular typescript or React user so please forgive me if my understanding is incorrect. But using just the web-component it appears that since format is not handled by the media-stream-player element, it falls back to the default still image.
https://github.com/AxisCommunications/media-stream-player-js/blob/master/lib/Player.tsx#L18

**Comment by lekoaf** [comment]
The WebComponent was a bit of an afterthought, so it looks like adding more properties was missed out. PRs are always welcome to fix the issue.

**Comment by AnderssonChristian** [comment]
Ah, you right. Not sure if that is intended though.

**Comment by steabert** [comment]
The web component is provided so you could have an easy player without having to concern yourself with React etc. However, the functionality is very limited, we should definitely add `autoplay` support and some way to easily add more options. I've marked this as feature request now.

**Comment by lekoaf** [comment]
Can verify that stats can't be dismissed and that the settings defaults to H264, but the stream is JPEG. Working on a fix for autoPlay though together with @steabert.
