### ISSUE TITLE
`fetchTransformationMatrix` - should be called with RTSP parameters in `HttpMp4Video` 

### ISSUE THREAD

**Issue by Tigge** [AxisCommunications/media-stream-player-js#171]
When calling `fetchTransformationMatrix` we should supply the same parameters as we do to the stream, so it will fetch the transformation matrix for the correct camera. See https://github.com/AxisCommunications/media-stream-player-js/blob/086e2cdec05dec93610a9d71317f9bee87192cb4/lib/HttpMp4Video.tsx#L132

**Comment by barnomasoz** [comment]
Should this issue be closed now since `fetchTransformationMatrix` has been removed?

**Comment by barnomasoz** [comment]
> When calling `fetchTransformationMatrix` we should supply the same parameters as we do to the stream, so it will fetch the transformation matrix for the correct camera. See
> 
> https://github.com/AxisCommunications/media-stream-player-js/blob/086e2cdec05dec93610a9d71317f9bee87192cb4/lib/HttpMp4Video.tsx#L132

Should this issue be closed now since fetchTransformationMatrix has been removed?

**Comment by Tigge** [comment]
Yes, function had been removed. Closing.
