### ISSUE TITLE
Removeing the overlay in the player

### ISSUE THREAD

**Issue by cubecleveland** [AxisCommunications/media-stream-player-js#188]
Hi, 

On player instanciation we get an overlay with the stats and bit rate...

How can i remove this ovelray from the player ?

**Comment by lekoaf** [comment]
```js
window.localStorage.setItem('stats-overlay',  'off')
```

It should however be off by default.

If you completely want to remove it, you'll have to use the building blocks to build your own Player and just not include the `<Stats />` component. Or use the `<BasicPlayer />` component. But that also means you lose a few other features.
