### ISSUE TITLE
Cannot use Player component in my project

### ISSUE THREAD

**Issue by jbentley10** [AxisCommunications/media-stream-player-js#20]
Hi there! 

I am working on a NextJS project, with the goal of simply displaying a video feed from an IP that I have. I am using the 'media-stream-library' and 'media-stream-player' packages in the project. 

I have a functional React component that I am building (called 'VideoFeed'), which is essentially the 'App.jsx' file from the examples/react-component directory in this project. 

My problem is that I am running into an error that seems to be coming from the package. The error says: 

```
at __webpack_require__ (/Users/johnbentley/Desktop/Projects/enable-live-video-prototype/.next/server/static/development/pages/_app.js:23:31)
/Users/johnbentley/Desktop/Projects/enable-live-video-prototype/node_modules/media-stream-player/dist/esm/index.js:1
import { MediaStreamPlayer } from './MediaStreamPlayer';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (vm.js:344:18)
    at wrapSafe (internal/modules/cjs/loader.js:1106:15)
```

My **VideoFeed.jsx** file looks like this: 

```
import { Player } from 'media-stream-player'
import React, { useState, useEffect } from 'react'
import styled from 'styled-components'
import PropTypes from 'prop-types';

const AppContainer = styled.div
  text-align: center;

const HostnameContainer = styled.div
  align-items: center;f
  display: inline-grid;
  grid-gap: 10px;
  grid-template-columns: auto 1fr;
  padding: 10px 0;


const DEFAULT_HOSTNAME = '192.168.0.90'

// force auth
const authorize = async (host) => {
  // Force a login by fetching usergroup
  try {
    await window.fetch(http://${host}/axis-cgi/usergroup.cgi, {
      credentials: 'include',
      mode: 'no-cors',
    })
  } catch (err) {
    console.error(err)
  }
}

const VideoFeed = (props) => {
  const {
    tagName: Tag,
    className,
    variant,
    children,
  } = props

  const [state, setState] = useState({
    authorized: false,
    hostname: localStorage.getItem('hostname') || DEFAULT_HOSTNAME,
  })

  let vapixParams = {}
  try {
    vapixParams = JSON.parse(window.localStorage.getItem('vapix')) ?? {}
  } catch (err) {
    console.warn('no stored VAPIX parameters: ', err)
  }

  useEffect(() => {
    if (!state.authorized) {
      authorize(state.hostname).then(() => {
        setState({ ...state, authorized: true })
      })
    }
  }, [state.authorized, state.hostname])

  return (
    <AppContainer>
      <h1>media-stream-player</h1>
      <HostnameContainer>
        <label htmlFor="hostname">Hostname</label>
        <input
          id="hostname"
          value={state.hostname}
          onChange={({ target: { value } }) => {
            setState({ authorized: false, hostname: value })
            localStorage.setItem('hostname', value)
          }}
        />
      </HostnameContainer>
      {state.authorized ? (
        <Player
          hostname={state.hostname}
          format="H264"
          autoPlay
          vapixParams={vapixParams}
        />
      ) : (
        <div>Not authorized</div>
      )}
    </AppContainer>
  )
}

VideoFeed.propTypes = {
  tagName: PropTypes.string,
  className: PropTypes.string,
  variant: PropTypes.oneOf(['default']),
  children: PropTypes.node,
}

VideoFeed.defaultProps = {
  tagName: 'div',
  className: '',
  variant: 'default',
  children: '',
}

export default VideoFeed
```

Is there anything I need to be doing in order to get the Player component to import and render correctly? Thank you so much!

**Comment by jbentley10** [comment]
Figured out the issue. You can't use Next.JS with this package because media-stream-player uses localStorage, and NextJS being a server-side framework will not run a module if it can't be rendered server-side. I used Create React App instead, and it worked like a charm. Thank you for this package!

**Comment by lekoaf** [comment]
Good find. `localStorage` is just used to persist settings between sessions. The library itself doesn't use the values, just persist them to make it easier for the developer to reuse them later. Perhaps we should investigate another way of doing this so that we can also support server side rendering, @steabert?

Somehow polyfill it or use another method if `window.localStorage` is `undefined`?

Save it in a `cookie` instead?

**Comment by steabert** [comment]
We should check if `localStorage` is available, otherwise just not use it. However, I don't see the immediate connection to the error?

**Comment by jbentley10** [comment]
Thank you both for looking into this issue! The initial error I received had to do with my webpack and Babel configurations. After playing around with some settings, I was able to diagnose the issue further down to LocalStorage. I look forward to trying out the package again!

**Comment by lekoaf** [comment]
@jbentley10, better late than never, but we merged a fix for the localStorage issue. Would love to get some feedback from you if you're interested in trying again.

We are not well versed in the whole server side rendering world, so would really appreciate to know if it works properly now.
