### ISSUE TITLE
 I have a question your repo apologies, directly supports rtsp connection in the hostname or do I have to use ws?

### ISSUE THREAD

**Issue by rogeliozx** [AxisCommunications/media-stream-player-js#28]
for example I convert an rtsp connection to a ws and use it this way with the JSMpeg library
example code:
`<canvas id="ine"></canvas>
    <script src="/jsmpeg.min.js"></script>
    <script>
      new JSMpeg.Player('ws://localhost:3001/stream', {
        canvas: document.getElementById('ine')
      });
    </script>`
but I have had many limitations to integrate it with react

**Comment by Tigge** [comment]
Hi. From Javascript is not possible able to directly connect to a port and read a RTSP data. You are limited to using websockets or similar methods to accomplish this. Note that jsmepg is another project, and is not affiliated with this one.

**Comment by rogeliozx** [comment]
excuse me what I mean is if your repository supports ws connection, if so could you show me a little example like since it's not in the doc,thank you very much for your response and your time too

**Comment by Tigge** [comment]
This player is designed to work with AXIS cameras, which have a websocket that can give you an RTSP stream. It does not work out of the box for other devices or random RTSP streams (even if they served over a websocket). It might be easier to start with https://github.com/AxisCommunications/media-stream-library-js in case you want to build something similar.
