### ISSUE TITLE
Missing .js?

### ISSUE THREAD

**Issue by greyfence** [AxisCommunications/media-stream-player-js#51]
I want to try the player but the media-stream-player.min.js just contains a link to another copy of the media-stream-player.min.js which does not appear exist in the repo.

**Comment by lekoaf** [comment]
Did you run "yarn dev" first?

**Comment by greyfence** [comment]
Well, no.  I just want to embed the player and the docs say "If you don't use the player as part of you React app, the easiest way to use it is to download the media-stream-player.min.js file".  Does this have to run through a server?

**Comment by lekoaf** [comment]
Yes, that's true. But you need to build the the minified file first, unless you install it trough npm.

**Comment by lekoaf** [comment]
Actually, running "yarn && yarn tsc" should suffice.

**Comment by greyfence** [comment]
"yarn && yarn tsc" created a bunch of typescript files in the dist folder but no .js files.

**Comment by lekoaf** [comment]
Okay. I'll take a look at that when I'm at work tomorrow. :)

**Comment by lekoaf** [comment]
Sorry, my bad. `yarn build` will do the trick. `media-stream-player.min.js` can then be found in the `dist` folder.

**Comment by lekoaf** [comment]
I belive the first problem is a known issue.

This library, nor the underlying media-stream-library, supports sound I think. Or am I wrong @steabert?

**Comment by greyfence** [comment]
I am able to get sound when using the simple.html sample from the media-stream-library-js-master project but the video is delayed by 2 or 3 seconds.  

I was really hoping for a much simpler method of streaming video with sound from Axis cameras to a browser.  I don't need any fancy interface, just bare video with sound.  Is there such a thing?

**Comment by lekoaf** [comment]
You can use the individual React components to just get the video. No controls, no menus or stats or any of that.

This is the simplest we got right now.

**Comment by steabert** [comment]
The simple embedding player doesn't support that much yet, it's mainly a matter of finding time or contributors to add features to the web component. But since there seems to be a larger interest in using this outside of React, we can try to to focus on getting more features in the web component part.
