### ISSUE TITLE
Video Player getting crashed

### ISSUE THREAD

**Issue by donny08** [AxisCommunications/media-stream-player-js#86]
I am trying to open camera in browser, but it is getting crashed. I am using example/react-app to run. I getting no error logs.

Please let me know if I have to do any configuration at camera side.

**Comment by lekoaf** [comment]
You'll have to give us a bit more than this to work with.

How did you run the example?

Did you clone this repository? Run yarn and yarn dev?
Open localhost?
Type what in the hostname input?

What kind of camera did you try and connect to?
What firmware does it have?

**Comment by donny08** [comment]
I copied the react-app/SingleStream.jsx file into my  newly created project , install required packages and run.

Hostname: 192.168.0.90.
Camera: Axis pinhole

**Comment by lekoaf** [comment]
Try running the examples from this repository instead. They are meant to give you an idea of how to use this library. Not to copy / paste in to your own project. I can't help you debug your problem if that's the case.

**Comment by lekoaf** [comment]
You may want to try out the web-component version instead.

**Comment by donny08** [comment]
Web version is working fine

**Comment by lekoaf** [comment]
Not sure why you deleted your other comments, but would you consider this issue resolved?

**Comment by lekoaf** [comment]
Closed due to inactivity. If this is still an issue, feel free to open it up again.
